server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal/shipping
    username: postgres
    password: simple123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: shippingSendSupplier
    stream:
      bindings:
        shippingSendEventListener-out-0:
          destination: shipping.send.exchange
          content-type: application/json
          producer:
            durable-expression: true

  management:
    endpoints:
      web:
        exposure:
          include: busrefresh